spring:
  datasource:
    generate-unique-name: false
    name: zaratestdb
    url: jdbc:h2:mem:zaratestdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties.hibernate.jdbc.time_zone: UTC
#    show-sql: true
    hibernate.ddl-auto: none
#logging.level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.hibernate.orm.jdbc.bind: trace