spring:

  h2:
    console:
      enabled: true
      path: /h2-console
  primary:
    datasource:
      jdbcUrl: jdbc:h2:mem:localhost;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: null
      driverClassName: org.h2.Driver
      auto-commit: false